version: '3.4'
services:
  mongo:
    image: 'mongo:3.6.5'
    container_name: 'llmcxt2_mongo'
    restart: always
    volumes:
      - './llmcxt2_mongo-data:/data/db'
  redis:
    image: 'redis:3.2.11'
    container_name: 'llmcxt2_redis'
    restart: always
    volumes:
      - './llmcxt2_redis-data:/data'
  llmcxt2:
    image: 'llmcxt2:v2.7'
    container_name: 'llmcxt2_app'
    restart: always
    ports:
      - '7001:7001'
    depends_on:
      - mongo
      - redis
